#!/bin/bash
# ~/.bash_login: executed by bash(1) for login shells. 
# This file is not read by bash(1), if ~/.bash_profile exists.

cd ~

if [ -f ".bash_login.local" ]; then
    source .bash_login.local
fi